apiVersion: 1

datasources:
  - name: MySQL-Hadoop
    uid: mysql-hadoop
    type: mysql
    url: mysql:3306
    database: universite
    user: root
    secureJsonData:
      password: root
    jsonData:
      maxOpenConns: 10
      maxIdleConns: 10
      connMaxLifetime: 14400
    isDefault: true
    editable: true
